Cars196:
  params:
    root: <WORKSPACE>/datasets
    phase: test
    assert_num_classes: 98
    assert_num_samples: 8131
    transform:
      - ~~_SEARCH_WITH_SAME_NAME_
      - transforms
      - null