MiniImageNet:
  params:
    root: <WORKSPACE>/datasets
    phase: test
    assert_num_classes: 20
    assert_num_samples: 12000
    transform:
      - ~~_SEARCH_WITH_SAME_NAME_
      - transforms
      - null