MiniImageNet:
  params:
    root: <WORKSPACE>/datasets
    phase: train
    assert_num_classes: 80
    assert_num_samples: 48000
    transform:
      - ~~_SEARCH_WITH_SAME_NAME_
      - transforms
      - null