MoCoCollector:
  params:
    query_trunk:
      - ~~_SEARCH_WITH_TARGET_NAME_
      - models
      - trunk
    query_embedder:
      - ~~_SEARCH_WITH_TARGET_NAME_
      - models
      - embedder
    metric: 
      - ~~_SEARCH_WITH_TARGET_NAME_
      - metrics
      - default
    bank_size: 65536
    embeddings_dim: 128
    m: 0.999
    T: 0.07