input: [data, embeddings, features, labels]
map: 
  loss_m:
    loss: 0
    weight: 1
  loss_reg:
    loss: 2
    weight: 3
  loss_hard:
    loss: 4
    weight: 5
  loss_adv:
    loss: 6
    weight: 7