input: [data, embeddings, features, labels]
map:
  loss_invariant:
      metric_mat: 0
      row_labels: 1
      col_labels: 2
      is_same_source: 3
  loss_syn: 
      metric_mat: 4
      row_labels: 1
      col_labels: 2
      is_same_source: 3
  loss_invariant: 
      weight: 10
  loss_syn:
      weight: 9
  loss_recon: 
      loss: 6
      weight: 8
  loss_kl: 
      loss: 5
      weight: 7