train_transforms:
  params:
    model_properties:
      - ~~_SEARCH_WITH_TARGET_NAME_
      - models
      - trunk
    compose_list:
      - RandomResizedCrop:
          scale: [0.2, 1.0]
          size: 224
      - RandomGrayscale:
          p: 0.2
      - ColorJitter:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.4
      - RandomHorizontalFlip: 
          p: 0.5
    wrapper: TwoCropsTransformWrapper