metrics:
  - default: euclid.yaml

collectors:
  - default: DVMLCollector.yaml

selectors:
  - default: DenseTripletSelector.yaml

losses:
  - default: TripletLoss.yaml

models:
  - trunk: googlenet.yaml
  - embedder: dvml_embedder.yaml
  - embedder_mean: dvml_embedder.yaml
  - embedder_std: dvml_embedder.yaml
  - decoder: dvml_decoder.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: Adam_trunk.yaml
  - embedder: Adam_embedder.yaml
  - embedder_mean: Adam_embedder.yaml
  - embedder_std: Adam_embedder.yaml
  - decoder: Adam_embedder.yaml

schedulers:
  - trunk: on_plateau.yaml
  - embedder: on_plateau.yaml
  - embedder_mean: on_plateau.yaml
  - embedder_std: on_plateau.yaml
  - decoder: on_plateau.yaml

gradclipper:
  - trunk: gradclipper.yaml
  - embedder: gradclipper.yaml
  - embedder_mean: gradclipper.yaml
  - embedder_std: gradclipper.yaml
  - decoder: gradclipper.yaml

transforms:
  - train: train_transforms.yaml
  - test: eval_transforms.yaml

datasets:
  - train: cub200_train.yaml
  - test: cub200_test.yaml

# samplers:
#   - train: MPerClassSampler.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING: 
  to_device_list: [models]
  to_wrap_list: [models]
