metrics:
  - default: cosine.yaml

collectors:
  - default: MultiProxyCollectorWithReg.yaml

selectors:
  - default: DefaultSelector.yaml

losses:
  - default: SoftTripleLoss.yaml

models:
  - trunk: bninception.yaml
  - embedder: bninception_mlp.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: AdamW_trunk.yaml
  - embedder: AdamW_embedder.yaml
  - proxy: AdamW_proxy.yaml

schedulers:
  - trunk: on_plateau.yaml
  - embedder: on_plateau.yaml
  - proxy: on_plateau.yaml

gradclipper:
  - trunk: gradclipper.yaml
  - embedder: gradclipper.yaml
  - proxy: gradclipper_collector.yaml

transforms:
  - train: train_transforms.yaml
  - test: eval_transforms.yaml

datasets:
  - train: cub200_train.yaml
  - test: cub200_test.yaml

# samplers:
#   - train: MPerClassSampler.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING: {}
