BaseRecorder:
  params:
    project_name: GeDML
    root: <WORKSPACE>/experiments/GeDML/test
    delete_old_folder: true
    hint_if_exist: true
    is_resume: false
    params_to_save: 
      - ~~_PASS_WITH_PARAMS_DICT_
      - none
      - none
    link_config:
      - ~~_PASS_WITH_LINK_CONFIG_
      - none
      - none