metrics:
  - default: moco.yaml

collectors:
  - collector: MoCoCollector.yaml

selectors:
  - selector: DefaultSelector.yaml

losses:
  - loss: CrossEntropyLoss.yaml

models:
  - trunk: mocov2_resnet50.yaml
  - embedder: mocov2_embedder.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: SGD_models.yaml
  - embedder: SGD_models.yaml

schedulers:
  - trunk: cosine_annealing_lr.yaml
  - embedder: cosine_annealing_lr.yaml

gradclipper:
  - trunk: gradclipper_models.yaml
  - embedder: gradclipper_models.yaml

transforms:
  - train: mocov2_train_transforms.yaml
  - test: mocov2_eval_transforms.yaml

datasets:
  - train: imagenet_train.yaml
  - test: imagenet_test.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING: 
  to_device_list: [models, collectors]
  to_wrap_list: [models]

PIPELINE_SETTING:
  - models/trunk/default -> models/embedder/
  - models/embedder/default -> collectors/collector/
  - collectors/collector/default -> selectors/selector/
  - selectors/selector/default -> losses/loss/
  - losses/loss/default -> FINISH/default/cross_entropy_loss
