metrics:
  - default: euclid.yaml

collectors:
  - collector: DefaultCollector.yaml

selectors:
  - selector: HardSelector.yaml

losses:
  - loss: MarginLoss.yaml

models:
  - trunk: bninception.yaml
  - embedder: bninception_mlp.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: AdamW_models.yaml
  - embedder: AdamW_models.yaml
  - loss: AdamW_losses.yaml

schedulers:
  - trunk: step_lr.yaml
  - embedder: step_lr.yaml
  - loss: step_lr.yaml

gradclipper:
  - trunk: gradclipper_models.yaml
  - embedder: gradclipper_models.yaml
  - loss: gradclipper_losses.yaml

transforms:
  - train: train_transforms.yaml
  - test: eval_transforms.yaml

datasets:
  - train: cub200_train.yaml
  - test: cub200_test.yaml

samplers:
  - train: MPerClassFullSampler.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING: 
  to_device_list: [models, losses]

PIPELINE_SETTING:
  - models/trunk/default -> models/embedder/
  - models/embedder/default -> collectors/collector/
  - collectors/collector/default -> selectors/selector/
  - selectors/selector/default -> losses/loss/
  - losses/loss/default -> FINISH/default/margin_loss