metrics:
  - default: euclid_normalized.yaml

collectors:
  - default: DefaultCollector.yaml

selectors:
  - default: HardSelector.yaml

losses:
  - default: MarginLoss.yaml

models:
  - trunk: bninception.yaml
  - embedder: MLP_bninception.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: AdamW_models.yaml
  - embedder: AdamW_models.yaml
  - default: AdamW_losses.yaml

schedulers:
  - trunk: step_lr.yaml
  - embedder: step_lr.yaml
  - default: step_lr.yaml

gradclipper:
  - trunk: gradclipper_models.yaml
  - embedder: gradclipper_models.yaml
  - default: gradclipper_losses.yaml

transforms:
  - train: train_transforms.yaml
  - test: eval_transforms.yaml

datasets:
  - train: cub200_train.yaml
  - test: cub200_test.yaml

# samplers:
#   - train: MPerClassSampler.yaml

collatefns:
  - train: default.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING: 
  to_device_list: [models, losses]

PIPELINE_SETTING:
  - models/trunk/default -> models/embedder/
  - models/embedder/default -> collectors/default/
  - collectors/default/default -> selectors/default/
  - selectors/default/default -> losses/default/
  - losses/default/default -> FINISH/default/loss