metrics:
  - default: cosine.yaml # todo

collectors:
  - default: MoCoCollector.yaml # to confirm

selectors:
  - default: DefaultSelector.yaml

losses:
  - default: PosPairLoss.yaml # todo 

models:
  - trunk: resnet50_scratch.yaml
  - embedder: mocov2_embedder.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: SGD_models.yaml # todo
  - embedder: SGD_models.yaml # todo
  - default: SGD_collectors.yaml # todo

schedulers:
  - trunk: step_lr.yaml # todo
  - embedder: step_lr.yaml # todo 
  - default: step_lr.yaml # todo

gradclipper:
  - trunk: gradclipper_models.yaml
  - embedder: gradclipper_models.yaml
  - default: gradclipper_collectors.yaml

transforms:
  - train: moco_train_transforms.yaml
  - test: moco_eval_transforms.yaml

datasets:
  - train: imagenet_train.yaml
  - test: imagenet_test.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING: 
  to_device_list: [models, collectors]
  to_wrap_list: [models, collectors]

PIPELINE_SETTING:
  - models/trunk/default -> models/embedder/
  - models/embedder/default -> collectors/default/
  - collectors/default/default -> selectors/default/
  - selectors/default/default -> losses/default/
  - losses/default/default -> FINISH/default/loss
