metrics:
  - default: cosine.yaml

collectors:
  - collector: ProxyCollector.yaml

selectors:
  - selector: DefaultSelector.yaml

losses:
  - loss: ProxyAnchorLoss.yaml

models:
  - trunk: bninception.yaml
  - embedder: bninception_mlp.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: AdamW_models.yaml
  - embedder: AdamW_models.yaml
  - collector: AdamW_collectors.yaml

schedulers:
  - trunk: step_lr.yaml
  - embedder: step_lr.yaml
  - collector: step_lr.yaml

gradclipper:
  - trunk: gradclipper_models.yaml
  - embedder: gradclipper_models.yaml
  - collector: gradclipper_collectors.yaml

transforms:
  - train: train_transforms.yaml
  - test: eval_transforms.yaml

datasets:
  - train: cub200_train.yaml
  - test: cub200_test.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING:
  to_device_list: [models, collectors]

PIPELINE_SETTING:
  - models/trunk/default -> models/embedder/
  - models/embedder/default -> collectors/collector/
  - collectors/collector/default -> selectors/selector/
  - selectors/selector/default -> losses/loss/
  - losses/loss/default -> FINISH/default/proxy_anchor_loss
  - collectors/collector/loss_reg -> FINISH/default/reg_loss